In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df['Message'],df['spam'],test_size=0.2)

In [7]:
X_train.shape

(4457,)

In [8]:
X_test.shape

(1115,)

In [9]:
type(X_train)

pandas.core.series.Series

In [12]:
X_train[:4][2672]

"That's cool, I'll come by like  &lt;#&gt; ish"

In [13]:
type(y_train)

pandas.core.series.Series

In [14]:
y_train[:4]

2672    0
3836    0
379     0
4780    0
Name: spam, dtype: int64

In [17]:
type(X_train.values)

numpy.ndarray

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_CV = v.fit_transform(X_train.values)
X_train_CV

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59335 stored elements and shape (4457, 7780)>

In [19]:
X_train_CV.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7780))

In [21]:
v.get_feature_names_out()[1000:1050]

array(['answr', 'antelope', 'anthony', 'anti', 'antibiotic', 'any',
       'anybody', 'anyhow', 'anymore', 'anyone', 'anyones', 'anythiing',
       'anythin', 'anything', 'anythingtomorrow', 'anytime', 'anyway',
       'anyways', 'anywhere', 'aom', 'apart', 'apartment', 'apes',
       'apeshit', 'aphex', 'apnt', 'apo', 'apologise', 'apologize',
       'apology', 'app', 'apparently', 'appeal', 'appear', 'appendix',
       'applausestore', 'applebees', 'application', 'apply', 'applyed',
       'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaching', 'appropriate', 'approved', 'approx',
       'apps'], dtype=object)

In [22]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [23]:
v.vocabulary_

{'that': 6822,
 'cool': 2015,
 'll': 4173,
 'come': 1916,
 'by': 1604,
 'like': 4124,
 'lt': 4260,
 'gt': 3280,
 'ish': 3762,
 'thinking': 6860,
 'chennai': 1781,
 'forgot': 2971,
 'to': 6951,
 'for': 2958,
 'auction': 1151,
 'keep': 3923,
 'my': 4683,
 'payasam': 5134,
 'there': 6844,
 'if': 3610,
 'rinu': 5800,
 'brings': 1529,
 'we': 7457,
 'cant': 1653,
 'see': 5994,
 'can': 1643,
 'join': 3851,
 'denis': 2247,
 'and': 973,
 'mina': 4496,
 'or': 4988,
 'does': 2388,
 'want': 7418,
 'alone': 933,
 'time': 6915,
 'im': 3627,
 'good': 3207,
 'have': 3377,
 'been': 1305,
 'about': 768,
 'you': 7748,
 'freemsg': 3007,
 'claim': 1831,
 'ur': 7231,
 '250': 373,
 'sms': 6270,
 'messages': 4470,
 'text': 6798,
 'ok': 4931,
 '84025': 677,
 'now': 4855,
 'use': 7250,
 'web2mobile': 7466,
 'mates': 4397,
 'etc': 2662,
 'txt250': 7123,
 'com': 1912,
 '50p': 552,
 'wk': 7596,
 'box139': 1477,
 'la32wu': 4002,
 '16': 321,
 'remove': 5705,
 'txtx': 7134,
 'stop': 6503,
 'thanks': 6815,
 'yesterday': 7734,
 'sir': 6189,
 'wonderful': 7618,
 'hope': 3508,
 'enjoyed': 2614,
 'the': 6826,
 'burial': 1580,
 'mojibiola': 4571,
 'sorry': 6335,
 'never': 4772,
 'hear': 3397,
 'unless': 7195,
 'book': 1445,
 'it': 3771,
 'one': 4956,
 'was': 7431,
 'kinda': 3954,
 'joke': 3854,
 'thet': 6850,
 'were': 7504,
 'really': 5617,
 'looking': 4211,
 'skinny': 6212,
 'white': 7533,
 'girls': 3163,
 'other': 5015,
 'line': 4138,
 'only': 4961,
 'do': 2378,
 'so': 6288,
 'much': 4648,
 'on': 4950,
 'camera': 1640,
 'with': 7586,
 'something': 6308,
 'they': 6851,
 're': 5599,
 'casting': 1694,
 'look': 4207,
 'still': 6490,
 'in': 3655,
 'area': 1063,
 'of': 4908,
 'restaurant': 5756,
 'ill': 3623,
 'try': 7084,
 'back': 1210,
 'soon': 6325,
 'welp': 7498,
 'apparently': 1031,
 'he': 3387,
 'retired': 5768,
 'someone': 6304,
 'know': 3974,
 'has': 3362,
 'asked': 1107,
 'our': 5022,
 'dating': 2178,
 'service': 6039,
 'contact': 1990,
 'guess': 3287,
 'who': 7535,
 'call': 1620,
 '09058095107': 185,
 'all': 923,
 'will': 7556,
 'be': 1284,
 'revealed': 5775,
 'pobox': 5284,
 's3xy': 5874,
 '150p': 309,
 'don': 2412,
 'no': 4810,
 'da': 2146,
 'whats': 7518,
 'plan': 5249,
 'jus': 3888,
 'telling': 6764,
 'dat': 2173,
 'leaving': 4079,
 'shanghai': 6070,
 '21st': 363,
 'instead': 3715,
 'haf': 3313,
 'more': 4597,
 'meet': 4437,
 'up': 7212,
 'cya': 2142,
 'congrats': 1974,
 'mobile': 4556,
 '3g': 467,
 'videophones': 7320,
 'yours': 7755,
 '09061744553': 204,
 'videochat': 7319,
 'wid': 7546,
 'play': 5258,
 'java': 3810,
 'games': 3092,
 'dload': 2375,
 'polyh': 5313,
 'music': 4673,
 'noline': 4823,
 'rentl': 5714,
 'bx420': 1602,
 'ip4': 3747,
 '5we': 578,
 '150pm': 311,
 'easy': 2522,
 'ah': 880,
 'sen': 6019,
 'got': 3222,
 'selected': 6006,
 'means': 4426,
 'its': 3778,
 'goal': 3187,
 'arsenal': 1092,
 'henry': 3430,
 'liverpool': 4168,
 'scores': 5956,
 'simple': 6173,
 'shot': 6125,
 'from': 3041,
 'yards': 7716,
 'pass': 5114,
 'bergkamp': 1338,
 'give': 3166,
 'margin': 4371,
 'after': 860,
 '78': 629,
 'mins': 4509,
 'here': 3433,
 'performance': 5169,
 'award': 1183,
 'is': 3759,
 'calculated': 1615,
 'every': 2680,
 'two': 7120,
 'month': 4590,
 'not': 4841,
 'current': 2125,
 'period': 5172,
 'attend': 1142,
 'driving': 2462,
 'lesson': 4097,
 'how': 3537,
 'many': 4362,
 'times': 6916,
 'which': 7529,
 'day': 2182,
 'wa': 7382,
 'efficient': 2549,
 'gee': 3120,
 'thanx': 6820,
 'sexy': 6054,
 'singles': 6185,
 'are': 1062,
 'waiting': 7395,
 'your': 7752,
 'age': 870,
 'followed': 2942,
 'gender': 3125,
 'as': 1098,
 'wither': 7588,
 '23f': 367,
 'gay': 3109,
 'men': 4457,
 '23g': 368,
 'sell': 6012,
 'tons': 6990,
 'coins': 1894,
 'then': 6838,
 'thru': 6893,
 'paypal': 5143,
 'voila': 7358,
 'money': 4581,
 'life': 4114,
 'pockets': 5297,
 'yo': 7743,
 'dude': 2485,
 'just': 3889,
 'arrested': 1087,
 'thought': 6877,
 'calling': 1632,
 'lot': 4225,
 'lil': 4129,
 'busy': 1590,
 'at': 1128,
 'noon': 4826,
 'takes': 6699,
 'me': 4420,
 'years': 7723,
 'shower': 6134,
 'where': 7524,
 'phone': 5203,
 'dead': 2189,
 'yet': 7735,
 'wanna': 7416,
 'some': 6300,
 'art': 1093,
 'mm': 4543,
 'had': 3311,
 'food': 2949,
 'out': 5025,
 'sense': 6026,
 'foot': 2953,
 'penis': 5159,
 'dont': 2416,
 'flatter': 2907,
 'yourself': 7756,
 'tell': 6763,
 'man': 4346,
 'mine': 4501,
 'pints': 5235,
 'carlin': 1677,
 'ten': 6774,
 'minutes': 4513,
 'please': 5266,
 'go': 3184,
 'perumbavoor': 5186,
 'congratulations': 1976,
 'awarded': 1184,
 '500': 547,
 'cd': 1712,
 'vouchers': 7366,
 '125gift': 292,
 'guaranteed': 3282,
 'free': 3001,
 'entry': 2629,
 '100': 260,
 'wkly': 7600,
 'draw': 2446,
 'txt': 7122,
 '87066': 695,
 'tncs': 6950,
 'www': 7681,
 'ldew': 4062,
 'com1win150ppmx3age16': 1913,
 'having': 3382,
 'great': 3254,
 'club': 1869,
 'choose': 1814,
 'any': 1005,
 'top': 7000,
 'quality': 5535,
 'items': 3774,
 '7cfca1a': 634,
 'her': 3432,
 'she': 6079,
 'doesnt': 2391,
 'reply': 5725,
 'let': 4099,
 'log': 4188,
 'reach': 5600,
 'home': 3493,
 'check': 1768,
 'errors': 2646,
 'difficulties': 2313,
 'correction': 2027,
 'week': 7480,
 'checking': 1771,
 'ups': 7226,
 '3days': 466,
 'also': 939,
 'shipping': 6098,
 'company': 1932,
 '2wks': 428,
 'way': 7452,
 'usps': 7258,
 'but': 1591,
 'when': 7521,
 'gets': 3142,
 'lag': 4010,
 'may': 4411,
 'bribe': 1519,
 'nipost': 4803,
 'get': 3139,
 'stuff': 6547,
 'thank': 6814,
 'skyped': 6219,
 'wit': 7585,
 'kz': 3994,
 'sura': 6631,
 'didnt': 2302,
 'pleasure': 5269,
 've': 7293,
 'given': 3167,
 'ultimatum': 7154,
 'oh': 4926,
 'countin': 2044,
 'down': 2435,
 'aburo': 776,
 'enjoy': 2613,
 'this': 6865,
 'message': 4469,
 'sent': 6028,
 'days': 2183,
 'ago': 878,
 'water': 7443,
 'logging': 4190,
 'desert': 2263,
 'geoenvironmental': 3135,
 'implications': 3643,
 'cthen': 2107,
 'thk': 6866,
 'shd': 6078,
 'enuff': 2632,
 'conclusion': 1960,
 'contents': 1997,
 'pg': 5194,
 'references': 5660,
 'doing': 2402,
 'cover': 2055,
 'hi': 3446,
 'darlin': 2167,
 'cantdo': 1654,
 'anythingtomorrow': 1014,
 'myparents': 4687,
 'aretaking': 1067,
 'outfor': 5030,
 'meal': 4421,
 'katexxx': 3915,
 'glad': 3170,
 'following': 2943,
 'dreams': 2450,
 'laid': 4011,
 'airtel': 895,
 'rest': 5755,
 'done': 2414,
 'next': 4782,
 'space': 6355,
 'gives': 3168,
 'everything': 2688,
 'remember': 5694,
 'furniture': 3073,
 'around': 1082,
 'move': 4616,
 'lock': 4185,
 'locks': 4186,
 'leave': 4077,
 'key': 3935,
 'jenne': 3823,
 'hey': 3442,
 'sweet': 6660,
 'wondering': 7619,
 'moment': 4575,
 'might': 4486,
 'send': 6020,
 'file': 2857,
 'won': 7614,
 'over': 5043,
 'yahoo': 7709,
 'them': 6834,
 'because': 1295,
 'their': 6831,
 'connection': 1979,
 'sucks': 6581,
 'set': 6043,
 'page': 5065,
 'download': 2436,
 'format': 2977,
 'disc': 2347,
 'could': 2040,
 'big': 1363,
 'files': 2858,
 'directly': 2334,
 'internet': 3727,
 'help': 3420,
 'would': 7649,
 'prey': 5420,
 'teasing': 6751,
 'kiss': 3960,
 'an': 968,
 'excellent': 2708,
 'misundrstud': 4533,
 'frnd': 3032,
 'knw': 3978,
 'hate': 3368,
 'bt': 1555,
 'wen': 7499,
 'truth': 7083,
 'urself': 7245,
 'gn': 3180,
 'weather': 7464,
 'students': 6542,
 'solved': 6299,
 'cat': 1697,
 'question': 5540,
 'xam': 7687,
 'answer': 996,
 'brilliant': 1524,
 '1thing': 345,
 'answr': 1000,
 'new': 4774,
 '0207': 10,
 '083': 62,
 '6089': 583,
 'nobody': 4813,
 'decide': 2203,
 'eat': 2523,
 'dad': 2149,
 'wants': 7422,
 'chinese': 1805,
 'yeah': 7721,
 'ride': 5789,
 'nothing': 4846,
 'spl': 6392,
 'wat': 7437,
 'abt': 774,
 'whr': 7542,
 'ru': 5849,
 'video': 7318,
 'handset': 3336,
 '750': 622,
 'network': 4767,
 'unlimited': 7197,
 'camcorder': 1638,
 '08000930705': 51,
 'del': 2231,
 'sat': 5922,
 'am': 947,
 'dear': 2194,
 'relieved': 5688,
 'westonzoyland': 7511,
 'going': 3196,
 'end': 2596,
 'too': 6991,
 'place': 5244,
 'need': 4747,
 'lar': 4030,
 'engin': 2610,
 'cos': 2030,
 'sis': 6191,
 'arts': 1094,
 'today': 6958,
 'pick': 5217,
 'fone': 2947,
 'dumb': 2491,
 'smile': 6258,
 'crucial': 2094,
 'things': 6856,
 'sometimes': 6310,
 'makes': 4338,
 'us': 7246,
 'forget': 2966,
 'gud': 3284,
 'text82228': 6799,
 'ringtones': 5799,
 'logos': 4195,
 'txt82228': 7125,
 'questions': 5542,
 'info': 3687,
 'co': 1882,
 'uk': 7149,
 'why': 7543,
 'god': 3190,
 'created': 2076,
 'gap': 3096,
 'between': 1348,
 'fingers': 2874,
 'made': 4313,
 'comes': 1918,
 'amp': 961,
 'fills': 2861,
 'those': 6873,
 'gaps': 3097,
 'holding': 3487,
 'hand': 3331,
 'love': 4238,
 'actually': 816,
 'full': 3060,
 'msg': 4630,
 'work': 7631,
 'online': 4960,
 'wil': 7553,
 'explain': 2737,
 'later': 4043,
 'finally': 2868,
 'came': 1639,
 'fix': 2895,
 'ceiling': 1716,
 'recpt': 5651,
 'ordered': 4996,
 'ringtone': 5797,
 'order': 4995,
 'being': 1321,
 'processed': 5452,
 'chat': 1758,
 '86688': 692,
 'find': 2871,
 'each': 2506,
 'rcvd': 5596,
 'hg': 3444,
 'suite342': 6595,
 '2lands': 403,
 'row': 5837,
 'w1j6hl': 7377,
 'ldn': 4063,
 '18': 325,
 'left': 4083,
 'dessert': 2269,
 'wan': 7413,
 'suntec': 6615,
 'aight': 889,
 'think': 6857,
 'blake': 1396,
 'address': 824,
 'occurs': 4902,
 'quite': 5546,
 'sure': 6632,
 'what': 7516,
 'chikku': 1792,
 'tke': 6936,
 'care': 1666,
 'sleep': 6224,
 'well': 7497,
 'nyt': 4885,
 'important': 3644,
 'customer': 2131,
 'announcement': 988,
 'premier': 5393,
 'shuhui': 6147,
 'say': 5937,
 'change': 1740,
 'steamboat': 6477,
 'noe': 4814,
 '07732584351': 29,
 'rodger': 5816,
 'burns': 1582,
 'tried': 7064,
 'nokia': 4820,
 'delivery': 2240,
 'tomorrow': 6978,
 'vijay': 7325,
 'talk': 6704,
 'jaya': 3812,
 'tv': 7111,
 'haven': 3379,
 'lost': 4224,
 'always': 945,
 '4u': 540,
 'didn': 2301,
 'intend': 3720,
 'hurt': 3574,
 'knew': 3970,
 'felt': 2829,
 'iwas': 3784,
 'marine': 4372,
 'itried2tell': 3777,
 'urmom': 7243,
 'careabout': 1667,
 'yes': 7732,
 'reg': 5669,
 'ciao': 1825,
 '200': 352,
 'even': 2673,
 '1000': 261,
 'cashto': 1691,
 '08000407165': 48,
 'getstop': 3144,
 '88222': 708,
 'php': 5212,
 'urgent': 7235,
 'number': 4870,
 'ukp': 7150,
 '2000': 353,
 'prize': 5438,
 '09061790125': 206,
 'landline': 4017,
 '3030': 439,
 'valid': 7276,
 '12hrs': 294,
 '150ppm': 313,
 'detroit': 2276,
 'snow': 6283,
 'fast': 2797,
 'xy': 7705,
 'suggest': 6591,
 'dun': 2492,
 'rain': 5563,
 'leh': 4087,
 'gd': 3117,
 'vl': 7352,
 'nice': 4785,
 'gas': 3103,
 'chance': 1738,
 'gang': 3095,
 'grand': 3242,
 'nature': 4727,
 'adventure': 842,
 'ask': 1105,
 'smth': 6273,
 'card': 1662,
 'present': 5405,
 'lei': 4088,
 'write': 7659,
 'sign': 6160,
 'engalnd': 2609,
 'telly': 6767,
 'decided': 2204,
 'watch': 7438,
 'mia': 4481,
 'elliot': 2574,
 'kissing': 3962,
 'damn': 2154,
 'people': 5161,
 'seems': 6000,
 'special': 6369,
 'first': 2888,
 'sight': 6159,
 'very': 7308,
 'few': 2836,
 'remain': 5692,
 'till': 6913,
 'last': 4037,
 'maintain': 4334,
 'ends': 2602,
 'sh': 6059,
 'jas': 3808,
 'lol': 4197,
 'dramatic': 2444,
 'schools': 5951,
 'already': 936,
 'closed': 1861,
 'drive': 2459,
 'inch': 3658,
 'supposed': 6628,
 'did': 2299,
 'his': 3458,
 'detailed': 2272,
 '87077': 697,
 'kick': 3941,
 'off': 4910,
 'season': 5979,
 'goals': 3188,
 'news': 4779,
 'name': 4704,
 'eg': 2551,
 'villa': 7330,
 'checked': 1769,
 'heading': 3391,
 'drop': 2465,
 'take': 6696,
 'xmas': 7691,
 'draws': 2447,
 'trying': 7086,
 'todays': 6959,
 'shows': 6138,
 '09058094565': 180,
 'land': 4015,
 'win': 7559,
 'weekly': 7484,
 'professional': 5455,
 'sport': 6408,
 'tiger': 6907,
 'woods': 7624,
 '87239': 702,
 'mum': 4658,
 'robinson': 5811,
 'stash': 6461,
 'ran': 5576,
 'dry': 2478,
 'night': 4793,
 'until': 7210,
 'sunday': 6607,
 'hot': 3524,
 'live': 4165,
 'fantasies': 2789,
 '08707500020': 87,
 '20p': 360,
 'per': 5163,
 'min': 4495,
 'ntt': 4864,
 'ltd': 4261,
 'po': 5282,
 'box': 1475,
 '1327': 297,
 'croydon': 2093,
 'cr9': 2060,
 '5wb': 577,
 '0870': 71,
 'national': 4723,
 'rate': 5584,
 'enjoying': 2616,
 'semester': 6016,
 'brother': 1542,
 'av': 1165,
 'ta': 6683,
 'ya': 7707,
 'ready': 5609,
 'thursday': 6899,
 'ou': 5021,
 'latest': 4044,
 '40gb': 488,
 'ipod': 3751,
 'mp3': 4623,
 'player': 5260,
 'word': 7629,
 'collect': 1902,
 '83355': 672,
 'ibhltd': 3587,
 'ldnw15h': 4064,
 'mtmsgrcvd18': 4644,
 'gonna': 3206,
 'death': 2198,
 'note': 4842,
 'says': 5941,
 'robs': 5812,
 'fault': 2805,
 'avenge': 1173,
 'innocent': 3700,
 'fun': 3063,
 '10': 259,
 'mths': 4641,
 'update': 7217,
 'phones': 5207,
 'same': 5903,
 'extra': 2748,
 'texts': 6809,
 'double': 2429,
 'txts': 7130,
 '6months': 612,
 'bluetooth': 1423,
 'orange': 4991,
 'available': 1168,
 'sony': 6322,
 'motorola': 4612,
 'mobileupd8': 4559,
 '08000839402': 50,
 'call2optout': 1622,
 'n9dx': 4693,
 'job': 3844,
 'bar': 1238,
 'airport': 894,
 'satsgettin': 5928,
 '47per': 514,
 'hour': 3530,
 'lie': 4112,
 'touch': 7018,
 'hello': 3417,
 'site': 6195,
 'songs': 6321,
 'pls': 5273,
 'make': 4337,
 'little': 4164,
 'spreadsheet': 6416,
 'track': 7028,
 'whose': 7541,
 'idea': 3601,
 'smoke': 6264,
 'determine': 2274,
 'smokes': 6266,
 'entire': 2625,
 'february': 2816,
 'claire': 1834,
 'havin': 3381,
 'borin': 1457,
 'cum': 2118,
 '2nite': 416,
 '09099725823': 250,
 'luv': 4276,
 'xx': 7695,
 'calls': 1634,
 'minmoremobsemspobox45po139wa': 4506,
 'meds': 4435,
 'once': 4954,
 'hours': 3532,
 'pain': 5069,
 'took': 6992,
 'another': 993,
 'die': 2304,
 'someday': 6303,
 'ad': 817,
 'crap': 2066,
 'nite': 4805,
 'without': 7590,
 'boggy': 1433,
 'boring': 1458,
 'biatch': 1360,
 'wait': 7392,
 'til': 6912,
 'nxt': 4881,
 'il': 3621,
 'ave': 1172,
 'miss': 4521,
 'vday': 7292,
 'parachute': 5090,
 'must': 4676,
 'burger': 1578,
 'killing': 3950,
 'fool': 2950,
 'cheat': 1765,
 'others': 5016,
 'drugdealer': 2471,
 'daddy': 2150,
 'scream': 5965,
 'slap': 6222,
 'ass': 1115,
 'dick': 2296,
 'outta': 5040,
 'class': 1840,
 'gym': 3304,
 'urgnt': 7238,
 'problem': 5444,
 'least': 4075,
 'wating': 7446,
 'afternoon': 862,
 'starshine': 6453,
 'boytoy': 1495,
 'crave': 2070,
 'ache': 798,
 'fuck': 3049,
 'sips': 6188,
 'cappuccino': 1657,
 'babe': 1202,
 'happens': 3350,
 'vegas': 7294,
 'stays': 6471,
 'wanted': 7420,
 'apartment': 1021,
 'late': 4040,
 'start': 6454,
 'omw': 4949,
 'right': 5790,
 'dunno': 2494,
 'watching': 7441,
 'boy': 1490,
 'loved': 4239,
 'gal': 3087,
 'propsd': 5482,
 'mind': 4498,
 'gv': 3302,
 'lv': 4281,
 'lttrs': 4263,
 'frnds': 3033,
 'threw': 6884,
 'thm': 6868,
 'again': 867,
 'aproach': 1053,
 'dt': 2480,
 'truck': 7075,
 'speeding': 6376,
 'towards': 7023,
 'wn': 7605,
 'hit': 3460,
 'girl': 3161,
 'hell': 3415,
 'saved': 5934,
 'hw': 3581,
 'cn': 1878,
 'run': 5862,
 'replied': 5723,
 'boost': 1452,
 'secret': 5985,
 'energy': 2605,
 'instantly': 3714,
 'shouted': 6129,
 'thy': 6901,
 'lived': 4166,
 'happily': 3351,
 '2gthr': 398,
 'drinking': 2456,
 'evrydy': 2701,
 'moral': 4596,
 'story': 6514,
 'hv': 3579,
 'msgs': 4636,
 'ni8': 4783,
 'haha': 3314,
 'sec': 5981,
 'anything': 1013,
 'samus': 5904,
 'shoulders': 6127,
 'ha': 3308,
 'popped': 5328,
 'loo': 4206,
 'ed': 2533,
 'sary': 5920,
 'tim': 6914,
 'bollox': 1437,
 'him': 3454,
 'tol': 6966,
 'played': 5259,
 'smash': 6251,
 'bros': 1540,
 'religiously': 5689,
 'blastin': 1401,
 'tsunamis': 7093,
 'occur': 4901,
 'rajnikant': 5571,
 'stopped': 6506,
 'swimming': 6667,
 'indian': 3677,
 'ocean': 4903,
 'joined': 3852,
 'itself': 3779,
 'mila': 4488,
 'age23': 872,
 'blonde': 1415,
 'sex': 6051,
 'guys': 3301,
 'mtalk': 4639,
 '69866': 601,
 '30pp': 440,
 '1st': 341,
 '5free': 569,
 '50': 546,
 'increments': 3671,
 'help08718728876': 3423,
 'pa': 5059,
 'panasonic': 5076,
 'bluetoothhdset': 1424,
 'doublemins': 2430,
 'doubletxt': 2432,
 'contract': 2001,
 '2optout': 417,
 'wkend': 7597,
 'journey': 3867,
 'terrible': 6785,
 'huge': 3557,
 'marking': 4376,
 'account': 794,
 'details': 2273,
 'mom': 4574,
 'wish': 7579,
 'wonders': 7620,
 'world': 7637,
 '7th': 639,
 '6th': 614,
 'style': 6553,
 '5th': 576,
 '4th': 536,
 'personality': 5181,
 '3rd': 476,
 ...}

In [26]:
v.get_feature_names_out()[1087]

'arrested'

In [28]:
X_train_np = X_train_CV.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4, 7780))

In [30]:
np.where(X_train_np[0]!=0)

(array([1604, 1916, 2015, 3280, 3762, 4124, 4173, 4260, 6822]),)

In [32]:
X_train[:4][2672]

"That's cool, I'll come by like  &lt;#&gt; ish"

In [33]:
X_train_np[0][1604]

np.int64(1)

In [34]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_CV,y_train)

MultinomialNB()

In [35]:
X_test_cv = v.transform(X_test)
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       982
           1       0.97      0.95      0.96       133

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [36]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [37]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [38]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [39]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       982
           1       0.97      0.95      0.96       133

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115